FROM node:21-bullseye

WORKDIR /app

RUN npm i -g pnpm
COPY ./package.json ./pnpm-lock.yaml ./
RUN pnpm install --ignore-scripts --frozen-lockfile --prefer-offline
COPY . .
RUN pnpm exec playwright install --with-deps chromium
